// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/app/sidebar.vue')['default']
    AppSidebarNavItem: typeof import('./src/components/app/sidebar/nav-item.vue')['default']
    BaseLayout: typeof import('./src/layouts/base-layout.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolLayout: typeof import('./src/layouts/tool-layout.vue')['default']
    ToolsRandomNumber: typeof import('./src/views/Tools/RandomNumber.vue')['default']
    ToolTitle: typeof import('./src/components/tool-title.vue')['default']
  }
}

export {}
