/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInput: typeof import('./../components/base-input.vue')['default']
    BaseNumberInput: typeof import('./../components/base-number-input.vue')['default']
    BaseSlider: typeof import('./../components/base-slider.vue')['default']
    BaseTextarea: typeof import('./../components/base-textarea.vue')['default']
    HeaderBrand: typeof import('./../components/header-brand.vue')['default']
    NavLink: typeof import('./../components/nav-link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/the-footer.vue')['default']
    TheHeader: typeof import('./../components/the-header.vue')['default']
    TheNav: typeof import('./../components/the-nav.vue')['default']
  }
}
